CHANGELOG will be later

diff --git a/rootfs/var/RunDir/utils/rim-dinteg b/rootfs/var/RunDir/utils/rim-dinteg
--- a/rootfs/var/RunDir/utils/rim-dinteg
+++ b/rootfs/var/RunDir/utils/rim-dinteg
@@ -1,4 +1,10 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
+
+RED='\033[1;91m'
+BLUE='\033[1;94m'
+GREEN='\033[1;92m'
+YELLOW='\033[1;33m'
+RESETCOLOR='\033[1;00m'
 
 HINTEG_DIR="$HOME/.local/share"
 HINTEG_APPS_DIR="$HINTEG_DIR/applications"
@@ -37,15 +43,33 @@ MIME_DIRS=(
     '/usr/share/mime/x-epoc'
 )
 
+nocolor() { sed -r 's|\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]||g' ; }
+
+error_msg() {
+    echo -e "${RED}[ ERROR ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
+    if [ "$NOT_TERM" == 1 ]
+        then notify-send -a 'RunImage Error' "$(echo -e "$@"|nocolor)" 2>/dev/null &
+    fi
+}
+
+info_msg() {
+    if [ "$RIM_QUIET_MODE" != 1 ]
+        then echo -e "${GREEN}[ INFO ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
+            if [[ "$NOT_TERM" == 1 && "$RIM_DONT_NOTIFY" != 1 ]]
+                then notify-send -a 'RunImage Info' "$(echo -e "$@"|nocolor)" 2>/dev/null &
+            fi
+    fi
+}
+
 lsapps() {
     local apps="$(grep -m1 '^Name=' -nr "$APPS_DIR" 2>/dev/null|\
-                  sed 's|.*:Name=||g;s|.*|"&"|g'|sort)"
+                  sed 's|.*:Name=||g;s|.*|"&"|g'|sort -u)"
     [ -n "$apps" ] && cat -n<<<"$apps"
 }
 
 lsintegapps() {
-    local apps="$(grep -m1 '^Name=.* \[RunImage\]' -nr "$HINTEG_APPS_DIR"/*-rimg.desktop 2>/dev/null|\
-                  sed 's|.*:Name=||g;s| \[RunImage\]$||g;s|.*|"&"|g'|sort)"
+    local apps="$(grep -m1 '^Name=.* \[RunImage\]' -nr "$HINTEG_APPS_DIR"/*-rim.desktop 2>/dev/null|\
+                  sed 's|.*:Name=||g;s| \[RunImage\]$||g;s|.*|"&"|g'|sort -u)"
     [ -n "$apps" ] && cat -n<<<"$apps"
 }
 
@@ -66,14 +90,14 @@ dinteg() {
                 then
                     unset postfix postfix_dir target exec_args
                     target="$(awk -F/ '{print$4}'<<<"$file")"
-                    postfix="$(cut -d'/' -f4-<<<"$file"|sed 's|.desktop$|-rimg.desktop|i;s|.png$|-rimg.png|i;s|.svg$|-rimg.svg|i;s|.xml$|-rimg.xml|i')"
+                    postfix="$(cut -d'/' -f4-<<<"$file"|sed 's|.desktop$|-rim.desktop|i;s|.png$|-rim.png|i;s|.svg$|-rim.svg|i;s|.xml$|-rim.xml|i')"
                     postfix_dir="$(dirname "$postfix")"
                     [ "$target" == 'menus' ] && \
                         HINTEG_DIR="$HOME/.config"
                     hinteg_file="${HINTEG_DIR}/${postfix}"
                     hinteg_file_dir="${HINTEG_DIR}/${postfix_dir}"
                     case "$act" in
-                        i)
+                        a)
                             mkdir $verb -p "$hinteg_file_dir"
                             cp $verb -f "$file" "$hinteg_file"
 
@@ -82,14 +106,10 @@ dinteg() {
                                     exec_args="env "
                                     [ -n "$RIM_OVERFS_ID" ] && \
                                     exec_args+="RIM_OVERFS_ID='$RIM_OVERFS_ID' "
-                                    #if [[ "$RUNSRCNAME" == "Run"* || \
-                                    #      "$RUNSRCNAME" == "runimage"* ]]
-                                    #    then exec_args+="'$RUNSRC' "
-                                    #fi
                                     exec_args+="'$RUNSRC' "
 
-                                    sed -i "s|^Icon.*|&-rimg|g;s|^Name.*|& [RunImage]|g;s|^Exec=|Exec=$exec_args|g;/^TryExec/d" "$hinteg_file"
-                                    chmod +x "$hinteg_file"
+                                    sed -i "s|^Icon.*|&-rim|g;s|^Name.*|& [RunImage]|g;s|^Exec=|Exec=$exec_args|g;/^TryExec/d" "$hinteg_file"
+                                    chmod $verb +x "$hinteg_file"
                             fi
                         ;;
                         r)
@@ -102,28 +122,47 @@ dinteg() {
     done
 }
 
-unset act ret
-case "$1" in
-    list|ls|l) shift
-            ret=1
-            case "$1" in
-                install|in|i) lsintegapps ;;
-                *) lsapps ;;
-            esac
-            if [ "$?" == 0 ]
-                then ret=0
-                else echo "No apps found!"
-            fi
-            exit $ret
-        ;;
-    install|in|i) shift ; act=i ;;
-    remove|rm|r) shift ; act=r ;;
-    *) echo "Unknown argument!" ; exit 1 ;;
-esac
+print_help() {
+    echo -e "[ Usage ]: desktop-integration [OPTIONS] {apps}
+
+[ Options ]:
+    -a, --add     [num|name|all|mime] Add applications to apps menu
+    -h, --help                        Show this message
+    -l, --list    [a|added]           List applications
+    -m, --mime                        With MIME types (env: RIM_DINTEG_WITH_MIME=1)
+    -v, --verbose                     Verbose output
+    -r, --remove  [num|name|all|mime] Remove applications from apps menu"
+    exit 1
+}
+
+unset act ret verb
+while [[ $# -gt 0 ]]
+    do
+        case "$1" in
+            -m|--mime   )   shift ; RIM_DINTEG_WITH_MIME=1 ;;
+            -v|--verbose)   shift ; verb='-v' ;;
+            -a|--add    )   shift ; act=a ;;
+            -r|--remove )   shift ; act=r ;;
+            -h|--help   )   print_help ;;
+            -l|--list   )   shift
+                            ret=1
+                            case "$1" in
+                                a|added) lsintegapps ;;
+                                *) lsapps ;;
+                            esac
+                            if [ "$?" == 0 ]
+                                then ret=0
+                                else error_msg "No apps found!"
+                            fi
+                            exit $ret
+                ;;
+            -*) error_msg "Unknown parameter: ${BLUE}$1\n"; print_help ;;
+            *) break ;;
+        esac
+done
 
 if [ -n "$1" ]
     then
-        verb='-v'
         case "$1" in
             hook) shift
                 unset verb
@@ -145,7 +184,7 @@ if [ -n "$1" ]
             ;;
             *)  IFS=$'\n'
                 app_list="$(case "$act" in
-                    i) lsapps ;;
+                    a) lsapps ;;
                     r) lsintegapps ;;
                 esac)"
                 for app in "$@"
@@ -157,18 +196,22 @@ if [ -n "$1" ]
                         integ_files=("$(grep -wm1 "^Name=$app_name$" -lr "$APPS_DIR" 2>/dev/null|head -1)")
                         if [ -n "$integ_files" ]
                             then
-                                echo "[ $app_name ]:"
+                                case "$act" in
+                                    a) act_info='Add' ;;
+                                    r) act_info='Remove' ;;
+                                esac
+                                info_msg "$act_info app: $app_name"
                                 icon_name="$(grep -m1 "^Icon=" "$integ_files" 2>/dev/null|sed 's|^Icon=||')"
                                 integ_files+=($(find_fl "$ICONS_DIR" -name "${icon_name}.*" 2>/dev/null))
                                 for file in "${integ_files[@]}";do echo "$file";done|dinteg
                             else
-                                echo "The app was not found!"
+                                error_msg "The app was not found: $([ "$app_name" ] && echo "$app_name"||echo "$app")"
                                 exit 1
                         fi)
                 done
             ;;
         esac
     else
-        echo "Specify the name or number of the app!"
+        error_msg "Specify the name or number of the app!"
         exit 1
 fi
